### ISSUE TITLE
Check this out tomorrow.

### ISSUE THREAD

**Issue by crystalchan2001** [crystalchan2001/SpotifyRecentsRecommender3000#4]
Enter the indexs of tracks [1-12] to use as seeds, separated by a space (Up to 5 indexes): _909_
Please enter indexes between 1 and 12: _i 9 9_
Traceback (most recent call last):
  File "C:\Users\chanc\Documents\2024\SpotifyPlaylist\createPlaylist.py", line 62, in <module>
    main()
  File "C:\Users\chanc\Documents\2024\SpotifyPlaylist\createPlaylist.py", line 25, in main
    indexes = validator.get_valid_seeds(input(f"Enter up to 5 indexes [1-{num_to_visualise}] of tracks to use as seeds, separated by a space: "), num_to_visualise)
  File "C:\Users\chanc\Documents\2024\SpotifyPlaylist\inputValidator.py", line 55, in get_valid_seeds
    invalid_seed_values = not all(self.is_in_range(int(idx), upBound) for idx in indexes)
  File "C:\Users\chanc\Documents\2024\SpotifyPlaylist\inputValidator.py", line 55, in <genexpr>
    invalid_seed_values = not all(self.is_in_range(int(idx), upBound) for idx in indexes)
ValueError: invalid literal for int() with base 10: 'i'

**Comment by crystalchan2001** [comment]
Fixed by changing input validitation using eval(i) to int(i)
